[package]
name = "get_interfaces"
version = "0.1.0"
edition = "2021"

[dependencies]
tray-icon = "0.11"
window-vibrancy = "0.4"
window-shadows = "0.2"
image = "0.24"
winit = "0.28"

[dependencies.windows]
version = "0.48"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]

[[bin]]
name = "get_interfaces"
path = "src/main.rs"
subsystem = "windows"
